### ISSUE TITLE
withDefaultConfig does not work properly with url connection strings

### ISSUE THREAD

**Issue by matt1097** [onebeyond/rascal#219]
## Description
Using the [Promise example](https://github.com/onebeyond/rascal/blob/master/examples/promises/index.js) code and the following two config files, I can get drastically different behavior.

url based connection string:
```
{
  "vhosts": {
    "/": {
      "connection": {
        "url": "amqp://guest:guest@HOST:5672/"
      }
    }
  }
}
```

parameters based connection string:
```
{
  "vhosts": {
    "/": {
      "connection": {
        "slashes": true,
        "protocol": "amqp",
        "hostname": "HOST",
        "user": "guest",
        "password": "guest",
        "port": 5672,
        "vhost": "/"
      }
    }
  }
}
```

When using the first file my connection details looks like:
<img width="971" alt="url-connect" src="https://github.com/onebeyond/rascal/assets/48395861/6bc67295-b00e-44cf-9b8c-388a2d389f14">

and with the second it is more like what i expect:
<img width="946" alt="parameter-connect" src="https://github.com/onebeyond/rascal/assets/48395861/6a1135ae-f1f5-4f7f-a75f-88db21d7e5bf">

Notice when using the URL based connection, that heart beat and channel max do not appear to be getting set properly from the [default config](https://github.com/onebeyond/rascal/blob/master/lib/config/defaults.js).

When using the parameter based connection, they are properly set to 10s and 100.

That is the observable behavior, I am unsure on if it is missing the other default options as well.

## Expected Behavior
Both connection methods should be properly using the default config

## Actual Behavior
Default config does not appear to be getting used when using the all-in-one url string connection method

## Steps to Reproduce

1. Start with your promises example
2. Run it once with each config and observe the connection details in your broker

## Context
Was troubleshooting unrelated heartbeat failures and noticed two applications had different values even though neither explicitly specified a heartbeat value in their configs and both were using withDefaultConfig(). Determined it was due to the difference in the connection method.

## Your Environment
* Version used: Seen in several versions including the latest 16.3.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Nodejs 18.9.0
* Operating System and version (desktop or mobile): Seen on Windows, Ubuntu, docker containers, etc.. does not seem to matter. 
* Broker: RabbitMQ running in a container. completely  stock fresh container from image: rabbitmq:3-management-alpine

**Comment by cressie176** [comment]
Thanks @matt1097, I'll take a look

**Comment by cressie176** [comment]
It's a very long time since I wrote this part of Rascal (8 years), however this was intended behaviour, and there's a [test](https://github.com/onebeyond/rascal/blob/master/test/config.tests.js#L54) to assert it.

I think my reasoning was that if you specify a URL, then you are no longer using default connection config. The presence or absence of options in the url is taken as what was intended. I can see how it is counter intuitive though.

I will give some thought as to whether it might be better to merge the default connection options with any query options specified in the url.

**Comment by cressie176** [comment]
I've updated Rascal's configuration to merge values source from a connection url with those provided as individual attributes, favouring the connection url if both are present.

At the same time I've made a few other hygiene changes, such as removing attributes from the connection properties that aren't directly related to amqp connections (e.g. `auth`, `query`, `pathname`), and regenerating the URL from the derived properties so that the url is consistence once all the defaults have been applied.

I'll release as v17 shortly.
